DeNA/Anjin

README.md, README_ja.md
Add meta-check and openupm badges.
=> Add badges

.github/workflows/actionlint.yml, .github/workflows/create-release-pr.yml, .github/workflows/metacheck.yml, .github/workflows/pr-labeler.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml
- Fix release-drafter trigger and concurrency
- Fix copyright
---
=> Fix release drafter workflow trigger and concurrency

README.md, README_ja.md
=> Fix typo s/dom.dena/com.dena/

Runtime/Agents/AbstractAgent.cs, Runtime/Agents/AbstractCompositeAgent.cs
Sometimes, I want to implement custom composite agents. It needs Random and Logger be injectable, but currently not. This patch make these injectable.
---
=> Make be able to implement custom composite agents

.editorconfig
see: https://youtrack.jetbrains.com/issue/RIDER-102981/File-Header-Template-variables-no-longer-being-replaced
---
=> Fix header template variables for Rider 2023.3

Editor/DeNA.Anjin.Editor.asmdef
Make the same setting as the Runtime assembly.
---
=> Turn off auto referenced in Editor assembly

Makefile, package.json
- Upgrade test-helper.monkey to v0.6.1 (needed for #19)
- Upgrade test-helper.random to v0.3.0
---
=> Upgrade test-helper.monkey to v0.6.1

Tests/Runtime/Agents/UGUIMonkeyAgentTest.cs
=> Fix test running on batchmode

Tests/Runtime/Agents/ParallelCompositeAgentTest.cs, Tests/Runtime/Agents/SerialCompositeAgentTest.cs
Fix conflicts #52 and #53 (both are mine...)
---
=> Fix logger using in tests

Runtime/Autopilot.cs
=> Fix CreateDefaultLogger method to private

Runtime/Agents/UGUIMonkeyAgent.cs
I forgot to set a `Logger` instance to `MonkeyConfig`.
---
=> Fix passing Logger instance to Monkey

.octocov.yml
- Ignore tests from "code" count
- Ignore under UnityProject~/Library/ from "code" and "test" count
---
=> Fix code-to-test-ratio settings in .octocov.yml

Editor/ContextMenu/DoCreateTitleOwnAssembly.cs
Fix to work with Unity 6 or newer.
---
=> Fix to work with Unity 6 or newer

Editor/Localization/ja.po, Editor/UI/Loggers/CompositeLoggerEditor.cs, Editor/UI/Loggers/ConsoleLoggerEditor.cs, Editor/UI/Loggers/FileLoggerEditor.cs, Editor/UI/Reporters/CompositeReporterEditor.cs, Editor/UI/Reporters/SlackReporterEditor.cs, README.md, README_ja.md
- Fix to do not translate keywords; Logger, Reporter; fixed #84 
- Fix case for Agent, Logger, and Reporter
- Add document for creating custom Logger and Reporter
Please merge this as soon as possible so it doesn't conflict with other PRs.
---
=> Fix documents about Logger and Reporter

Runtime/Autopilot.cs, Runtime/Settings/AutopilotSettings.cs, Tests/Runtime/Settings/AutopilotSettingsTest.cs
- Fix Loggers and Reporters convert, set to field directly to avoid complicating the state
- Fix SlackReporter convert condition and create the file. Same as a JUnitXmlReporter; see #98
I hope to your review && merge ASAP.
---
=> Fix obsolete fields convert spec

Editor/Commandline.cs, Runtime/Launcher.cs, Runtime/Settings/ArgumentCapture/ArgumentCapture.cs, Runtime/Settings/AutopilotSettings.cs, Tests/Runtime/AutopilotTest.cs, Tests/Runtime/Settings/AutopilotSettingsTest.cs, Tests/TestAssets/AutopilotSettings2sec.asset, Tests/TestAssets/AutopilotSettingsInfinity.asset
- Fix mistake rebase in #97
- Fix to unify the call for applying command-line args into a single entry point
- Fix misspelling internal method name
- Migrate test setting asset files
I hope to your review && merge ASAP.
---
=> Fix convert SceneCrossingAgents settings

.github/workflows/conflibot.yml
conflibot is check conflict exists (not merged yet) pull-requests
If a conflict is found, it will not result in an error but will be output to checks.
see:
- https://github.com/wktk/conflibot
- https://wktk.jp/entry/introducing-conflibot/
---
=> Add conflibot workflow

Editor/UI/Settings/AutopilotSettingsEditor.cs, README.md, README_ja.md, Runtime/DeNA.Anjin.asmdef, Runtime/Launcher.cs, Runtime/Reporters/MessageBuilder.cs, Runtime/Settings/AutopilotState.cs
Support [Multiplayer Play Mode](https://docs.unity3d.com/Packages/com.unity.multiplayer.playmode@latest) (MPPM) package.
- Sync `AutopilotState` with virtual players of MPPM package; Save an asset when changing state
- Add placeholder "{mppm-tags}" into `SlackReporter`
---
=> Support Multiplayer Play Mode (MPPM) package

Tests/Runtime/Agents/UGUIEmergencyExitAgentTest.cs
Fixed test that takes a screenshot.
This test failed to run on batchmode.
---
=> Fix test that takes a screenshot

Editor/Commandline.cs, Editor/DeNA.Anjin.Editor.asmdef, README.md, README_ja.md, Runtime/Settings/Arguments.cs
Add command line arguments to set `GameView` resolution.
---
=> Add GameView resolution command line arguments

Runtime/Agents/AbstractAgent.cs, Runtime/Agents/ErrorHandlerAgent.cs, Runtime/Agents/TerminateAgent.cs, Runtime/Agents/TimeBombAgent.cs, Runtime/Agents/UGUIMonkeyAgent.cs, Tests/Runtime/Agents/ErrorHandlerAgentTest.cs, Tests/Runtime/Agents/TerminateAgentTest.cs, Tests/Runtime/Agents/TimeBombAgentTest.cs, Tests/Runtime/Agents/UGUIMonkeyAgentTest.cs
Pull up `_autopilot` fields in each Agent to `AbstractAgent`.
I hope to your review && merge && release around one week.
---
=> Refactor: pull up _autopilot fields to AbstractAgent

Runtime/AgentDispatcher.cs, Tests/Runtime/AgentDispatcherTest.cs
Dispatch only one Agent if multiple Agents mapped the same scene.
Dispatch all Agents if multiple Agents mapped the same scene.
I hope to your review && merge && release it in around one week.
---
=> Fix to dispatch multiple Agents mapped the same scene

Runtime/Agents/UGUIEmergencyExitAgent.cs, Tests/Runtime/Agents/UGUIEmergencyExitAgentTest.cs
`UGUIEmergencyExitAgent` click even if the `EmergencyExitAnnotation` is disabled.
`UGUIEmergencyExitAgent` does not click if the `EmergencyExitAnnotation` is disabled.
Test results: https://github.com/nowsprinting/Anjin/actions/runs/13392868417
Low.
---
=> Fix to ignore disabled EmergencyExitAnnotation

.github/workflows/test.yml, package.json
- Upgrade dependency package test-helper.monkey from v0.13.2 to v0.14.0
Release notes:
- https://github.com/nowsprinting/test-helper.monkey/releases/tag/v0.14.0
- https://github.com/nowsprinting/test-helper.monkey/releases/tag/v0.13.4
- https://github.com/nowsprinting/test-helper.monkey/releases/tag/v0.13.3
Test results:
- https://github.com/nowsprinting/Anjin/actions/runs/13391301564
Please review and merge it ASAP.
But don't release it yet.
I have the next PR based on this.
---
=> Upgrade dependency package test-helper.monkey from v0.13.2 to v0.14.0; Support TMPro.TMP_InputField

.github/workflows/actionlint.yml, .github/workflows/create-release-pr.yml, .github/workflows/metacheck.yml, .github/workflows/pr-labeler.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml, .github/workflows/test.yml
- Pin GitHub Actions SHA
- see: [GitHub Actionsの外部Actionのバージョンをhash指定にし、可読性を維持しつつバージョンを上げる - Hatena Developer Blog](https://developer.hatenastaff.com/entry/2025/03/17/200642)
Very low
---
=> Pin GitHub Actions SHA

.github/dependabot.yml
Update Dependabot configuration for security updates only.
---
=> Update Dependabot configuration for security updates only
