.github/workflows/pr-labeler.yml

When PR from public fork, Can not access configuration file in `pull_request` trigger.
e.g., https://github.com/DeNA/Anjin/actions/runs/4633726453
`pull_request_target` trigger is:
- GITHUB_TOKEN is granted read/write repository permission unless the permissions key is specified and the workflow can access secrets, even when it is triggered from a fork
- Runs in the context of the base of the pull request (NOT merge commit)
Refs:
- https://github.com/TimonVS/pr-labeler-action/issues/25#issuecomment-891051406
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
---

Change pr-labeler workflow trigger to pull_request_target

---

Runtime/Reporters/SlackReporter.cs

SlackReporter screenshot process now performs Apply after copying the texture content.
I am using SetPixels() to remove the alpha channel from a texture in a screenshot.
I have to execute Apply() after using this method, but I forgot to do it.
-> https://docs.unity3d.com/ja/2019.4/ScriptReference/Texture2D.Apply.html
However, it works fine even if Apply() is not executed, so this is an insurance measure as well.
This is in anticipation of problems that may occur in some environments.

forgot to call Apply on the texture copy of the screenshot

---

Tests/TestAssets/DoNothingAgentForTests.asset

- Test asset name (not displayed in inspector window)
- Forgot to change
---

Fix test asset name

---

Editor/DeNA.Anjin.Editor.asmdef
Editor/UI/Settings/AutopilotSettingsEditor.cs
Runtime/AgentDispatcher.cs
Runtime/Autopilot.cs
Runtime/Utilities/LogMessageHandler.cs
Tests/Runtime/LauncherTest.cs
Tests/Runtime/TestDoubles/StubClickAgent.cs
Tests/Runtime/TestDoubles/StubClickAgent.cs.meta
Tests/Runtime/TestDoubles/StubThrowingErrorOnClick.cs
Tests/Runtime/TestDoubles/StubThrowingErrorOnClick.cs.meta
Tests/TestAssets/AutopilotSettingsForFacingImmediatelyError.asset
Tests/TestAssets/AutopilotSettingsForFacingImmediatelyError.asset.meta
Tests/TestAssets/StubClickAgentForTests.asset
Tests/TestAssets/StubClickAgentForTests.asset.meta
Tests/TestAssets/StubImmediatelyErrorAgentForTests.asset
Tests/TestAssets/StubImmediatelyErrorAgentForTests.asset.meta
Tests/TestScenes/Error.unity
Tests/TestScenes/Error.unity.meta

1. Checkout to [f5eaf92](https://github.com/DeNA/Anjin/pull/20/commits/f5eaf92657b56fd47c12d07ed68f746c59aab586)
2. Keep state not playing
3. Open the scene "Error"
4. Open an inspector for "AutopilotSettingsForFacingImmediatelyError"
5. Click Run
Stop playing and report the error to Slack.
Still playing and did not report to Slack.
---

Fix not stopping and reporting when error occurred

---

Runtime/Autopilot.cs
Runtime/Utilities/LogMessageHandler.cs
Tests/Runtime/TestDoubles/StubThrowingErrorFromNotMainThreadOnClick.cs
Tests/Runtime/TestDoubles/StubThrowingErrorFromNotMainThreadOnClick.cs.meta
Tests/TestAssets/StubClickAgentForTests.asset
Tests/TestScenes/Error.unity

1. Checkout [b573d0a](https://github.com/DeNA/Anjin/pull/21/commits/b573d0a1cc5b8e18e39525b90d2bc22a12e359d6)
2. Stay keep state not playing
3. Open the scene "Error"
4. Open an inspector for "AutopilotSettingsForFacingImmediatelyError"
5. Click Run
Stop playing and report the error to Slack.
Still playing and did not report to Slack.
---

Fix not reported when log from not main thread

---

Runtime/Reporters/SlackReporter.cs
Tests/Runtime/TestDoubles/StubClickAgent.cs

- `String.Split(string)` overload is added .NET Standard 2.1
- `GameObject.FindObjectsByType<t>` is added Unity 2020.3.4, 2021.3.18, 2022.2.5 or later.
---

Fix for older Unity

---

Editor/Commandline.cs
README.md
README_ja.md
Runtime/Reporters/SlackMessageSender.cs
Tests/Runtime/DeNA.Anjin.Tests.asmdef
Tests/Runtime/Reporters/SlackMessageSenderTest.cs

- Support take screenshot on batchmode. fixed #25
- Show GameView window when launching on batchmode. see: https://www.nowsprinting.com/entry/2023/06/14/003659
---

Support run on batchmode

---

Editor/Localization/ja.po
Editor/UI/Agents/TimeBombAgentEditor.cs
Editor/UI/Agents/TimeBombAgentEditor.cs.meta
README.md
README_ja.md
Runtime/Agents/TimeBombAgent.cs
Runtime/Agents/TimeBombAgent.cs.meta
Tests/Runtime/Agents/TimeBombAgentTest.cs
Tests/Runtime/Agents/TimeBombAgentTest.cs.meta
Tests/Runtime/TestComponents.meta
Tests/Runtime/TestComponents/OutGameTutorialButton.cs
Tests/Runtime/TestComponents/OutGameTutorialButton.cs.meta
Tests/TestScenes/OutGameTutorial.unity
Tests/TestScenes/OutGameTutorial.unity.meta

- Add `TimeBombAgent`
An Agent that will fail if a defuse message is not received before the inner agent exits.
For example, pass the out-game tutorial (Things that can be completed with tap operations on uGUI, such as smartphone games).
1. Set `UGUIMonkeyAgent` as the `Agent`. It should not be able to operate except for the advancing button. Set the `Lifespan Sec` with a little margin.
2. Set the log message to be output when the tutorial is completed as the `Defuse Message`.
This Agent instance (.asset file) can contain the following.
<dl>
<dt>Agent</dt><dd>Working Agent. If this Agent exits first, the TimeBombAgent will fail.</dd>
<dt>Defuse Message</dt><dd>Defuse the time bomb when this message comes to the log first. Can specify regex.</dd>
</dl>
---

Add TimeBombAgent helpful pass the out-game tutorial using MonkeyAgent

---

.editorconfig
Editor/Commandline.cs
Editor/UI/Settings/AutopilotSettingsEditor.cs
README.md
README_ja.md
Runtime/Autopilot.cs
Runtime/ExitCode.cs
Runtime/ExitCode.cs.meta
Runtime/LaunchType.cs
Runtime/LaunchType.cs.meta
Runtime/Launcher.cs
Runtime/LauncherFromTest.cs
Runtime/LauncherFromTest.cs.meta
Runtime/Settings/AutopilotState.cs
Runtime/Utilities/LogMessageHandler.cs
Tests/Runtime/LauncherFromTestTest.cs
Tests/Runtime/LauncherFromTestTest.cs.meta
Tests/Runtime/LauncherTest.cs

- Add launcher from test
- Refactor enum
Autopilot works within your test code using the async method `LauncherFromTest.AutopilotAsync(string)`.
Specify the `AutopilotSettings` file path as the argument.
```
[Test]
public async Task LaunchAutopilotFromTest()
{
await LauncherFromTest.AutopilotAsync("Assets/Path/To/AutopilotSettings.asset");
}
```
> [!NOTE]  
> If an error is detected in running, it will be output to `LogError` and the test will fail.
> [!WARNING]  
> The default timeout for tests is 3 minutes. If the autopilot execution time exceeds 3 minutes, please specify the timeout time with the `Timeout` attribute.
---

Support launch autopilot from Play Mode tests

---

Editor/Localization/ja.po
Editor/UI/Agents/UGUIMonkeyAgentEditor.cs
Runtime/Agents/UGUIMonkeyAgent.cs
package.json

- Upgrade test-helper.monkey package to [v0.11.0](https://github.com/nowsprinting/test-helper.monkey/releases/tag/v0.11.0)
- Fix accept `MonkeyConfig` changes
- Fix editor layout
---

Upgrade test-helper.monkey package to v0.11.0 (pluggable operators)

---

Runtime/Agents/UGUIMonkeyAgent.cs
Tests/Runtime/Agents/UGUIMonkeyAgentTest.cs
Tests/Runtime/DeNA.Anjin.Tests.asmdef

Screenshots filename prefix is Always "Run_" when `defaultScreenshotFilenamePrefix` is true.
Use agent name instead of `[CallerMemberName]`.
(That's what the README says!)
---

Fix default screenshots filename prefix to agent name

---

Runtime/Agents/DoNothingAgent.cs
Runtime/Agents/EmergencyExitAgent.cs
Runtime/Agents/OneTimeAgent.cs
Runtime/Agents/ParallelCompositeAgent.cs
Runtime/Agents/RepeatAgent.cs
Runtime/Agents/SerialCompositeAgent.cs
Runtime/Agents/TimeBombAgent.cs
Runtime/Agents/UGUIMonkeyAgent.cs
Tests/Runtime/Agents/DoNothingAgentTest.cs
Tests/Runtime/Agents/EmergencyExitAgentTest.cs
Tests/Runtime/Agents/OneTimeAgentTest.cs
Tests/Runtime/Agents/ParallelCompositeAgentTest.cs
Tests/Runtime/Agents/RepeatAgentTest.cs
Tests/Runtime/Agents/SerialCompositeAgentTest.cs
Tests/Runtime/Agents/TimeBombAgentTest.cs
Tests/Runtime/Agents/UGUIMonkeyAgentTest.cs
Tests/Runtime/Agents/UGUIPlaybackAgentTest.cs

Agents do not output exit log if canceled.
Agents output exit log always.
---

Fix agents do not output exit log if canceled

---

Runtime/AgentDispatcher.cs
Runtime/Autopilot.cs
Tests/Runtime/AgentDispatcherTest.cs
Tests/Runtime/TestDoubles/SpyAliveCountAgent.cs
Tests/Runtime/TestDoubles/SpyAliveCountAgent.cs.meta

Fixed two bugs.
Duplicate agent creation.
1. Load and activate scene-A, creation agent-A
2. Load scene-B additive and activate (scene-A and agent-A remain)
3. Re-activate scene-A
Agent creation when `SceneManager.activeSceneChanged`.
Agent creation when `SceneManager.sceneLoaded`.
Not dispatch (creation) observer agent.
Specify observer agent, but not specify fallback agent.
Return before creating observer agent when not specified fallback agent.
Create observer agent even if fallback agent is not specified.
---

Fix duplicate agent creation when reactivating scene

---

Tests/Runtime/Agents/OneTimeAgentTest.cs

Remove call `LogAssert.NoUnexpectedReceived` from `Run_wasExecuted_notExecuteChildAgent` test method.
When running all tests, may be failing this test because the following logs picked up:
```
[Log] There are 2 audio listeners in the scene. Please ensure there is always exactly one audio listener in the scene.
```
---

Fix OneTimeAgent test

---

Runtime/Autopilot.cs
Runtime/Utilities/LogMessageHandler.cs

Duplicate agent creation.
1. **Stop Play Mode** after Launch autopilot on editor window
2. Re-launch autopilot
`SceneManager.sceneLoaded` event listener is not removed. Because it does not call `Autopilot.TerminateAsync` when stopping Play Mode.
Remove event listeners on destroying `Autopilot` object.
No way to write effective test code for this change.
Refactor: Fix to add/remove `Application.logMessageReceivedThreaded` event listener on inside `LogMessageHandler`.
---

Fix to remove event listeners on destroying Autopilot object

---

Runtime/Agents/ParallelCompositeAgent.cs
Runtime/Agents/SerialCompositeAgent.cs
Tests/Runtime/Agents/ParallelCompositeAgentTest.cs
Tests/Runtime/Agents/SerialCompositeAgentTest.cs

1. NullReferenceException
2. Freeze Unity editor
1. CompositeAgent includes "None" entity
2. CompositeAgent includes itself entity
Not excluding null and itself.
Excluding null and itself.
---

Fix CompositeAgent includes null and itself agent case

---

package.json

- Upgrade test-helper.monkey package to [v0.12.0](https://github.com/nowsprinting/test-helper.monkey/releases/tag/v0.12.0) (Optimize logging)
- Optimize package.json
---

Upgrade test-helper.monkey to v0.12.0 (Optimize logging)

---

Runtime/Utilities/JUnitReporter.cs
Tests/Runtime/Utilities/JUnitReporterTest.cs

When generics are included in the stack trace, `<` and `>` are inserted.
---

Add mark stack traces with CDATA in JUnit XML report

---

Runtime/Reporters/AbstractReporter.cs
Runtime/Reporters/CompositeReporter.cs
Runtime/Reporters/SlackMessageSender.cs
Runtime/Reporters/SlackReporter.cs
Runtime/Settings/AutopilotSettings.cs
Runtime/Utilities/LogMessageHandler.cs
Tests/Runtime/TestDoubles/SpyReporter.cs

- Fix not to send body when stack-trace is empty
- Remove suppress diagnostic for obsolete fields
- Remove `AutopilotSettings` from parameter of `PostReportAsync`
---

Not to send body when stack-trace is empty

---

README.md
README_ja.md
Runtime/Loggers/FileLoggerAsset.cs
Runtime/Settings/Arguments.cs
Tests/Runtime/Loggers/FileLoggerAssetTest.cs

- Add command line argument `-FILE_LOGGER_OUTPUT_PATH`. Overwrite the `outputPath` of `FileLogger`
- Fix READMEs for `SlackReporter`
- Fix case of `outputPath` without directory
- Fix case of `outputPath` is not set
---

Add command line argument -FILE_LOGGER_OUTPUT_PATH

---

README.md
README_ja.md
Runtime/Utilities/LogMessageHandler.cs
Tests/Runtime/Utilities/LogMessageHandlerTest.cs

Make "Ignore Messages" can be specified by regex.
ASAP
---

Make ignore-messages can be specified by regex

---

Runtime/Loggers/ConsoleLoggerAsset.cs
Runtime/Loggers/FileLoggerAsset.cs
Tests/Runtime/Loggers/ConsoleLoggerAssetTest.cs
Tests/Runtime/Loggers/FileLoggerAssetTest.cs
Tests/TestAssets/ConsoleLogger.asset
Tests/TestAssets/ConsoleLogger.asset.meta
Tests/TestAssets/FileLogger.asset
Tests/TestAssets/FileLogger.asset.meta

Crean logger asset instances when launching autopilot.
This change will fix the following problems:
- Not reflected changes in logger settings
- FileLogger: No output file generated
Conditions:
Turn off "Reload Domain" (Project settings > Enter Play Mode Options).
And running the game more than once while the Unity editor is running.
---

Crean logger instances when launch autopilot

---

Runtime/Utilities/LogMessageHandler.cs

Fix the `new` expression to work with Unity 2020 or lower.
refs #67 
---

Fix expression to work with Unity 2020 or lower

---

Makefile

After July 2024, specifying the `@latest` dist-tag (default) will install the test-framework package v2.
`@stable` virtual dist-tag is support from opeupm-cli v4.3.0 or later.
see: https://github.com/openupm/openupm-cli/issues/395
`-c` option has been changed from global to local option of add/remove subcommands.
see: https://github.com/openupm/openupm-cli/discussions/408
---

Add `@stable` virtual dist-tag when installing test-framework package

---

README.md
README_ja.md
Runtime/Agents/UGUIMonkeyAgent.cs
Runtime/Launcher.cs
Runtime/Strategies.meta
Runtime/Strategies/TwoTieredCounterStrategy.cs
Runtime/Strategies/TwoTieredCounterStrategy.cs.meta
Tests/Runtime/Agents/UGUIMonkeyAgentTest.cs
Tests/Runtime/DeNA.Anjin.Tests.asmdef
Tests/Runtime/LauncherTest.cs
Tests/Runtime/Strategies.meta
Tests/Runtime/Strategies/TwoTieredCounterStrategyTest.cs
Tests/Runtime/Strategies/TwoTieredCounterStrategyTest.cs.meta
Tests/Runtime/TestDoubles/SpyInitializeOnLaunchAutopilot.cs

UGUIMonkeyAgent default screenshot filename is:
- MyMonkeyAgent_0001.png
- MyMonkeyAgent_0002.png
:
If the same Agent named `MyMonkeyAgent` is run again, the filename will be duplicated (the screenshot will be overwritten).
UGUIMonkeyAgent default screenshot filename is:
- MyMonkeyAgent01_0001.png
- MyMonkeyAgent01_0002.png
:
If the same Agent named `MyMonkeyAgent` is run again, the filename will be unique.
- MyMonkeyAgent02_0001.png
- MyMonkeyAgent02_0002.png
:
This strategy is not needed in test-helper.monkey, so I implemented it inside Anjin.
---

Change UGUIMonkeyAgent default screenshot filename strategy to TwoTieredCounterStrategy

---

Runtime/AgentDispatcher.cs
Runtime/Autopilot.cs
Tests/Runtime/AgentDispatcherTest.cs
Tests/Runtime/AutopilotTest.cs
Tests/TestScenes/Empty.unity
Tests/TestScenes/Empty.unity.meta

Launch autopilot while in play mode or running player build.
Multiple scenes are loaded, but the scene the agent is mapped to is not active (it is loaded).
Did not dispatch agent.
Dispatch agent mapped in the loaded (not active) scene.
Check mapping all loaded scenes if active scene is not mapped on launch.
I want it to be released at the same time as #76 
---

Fix to do dispatch agent if mapped scene is not active when launching autopilot

---

Editor/Localization/ja.po
Editor/UI/Reporters/CompositeReporterEditor.cs
Editor/UI/Reporters/SlackReporterEditor.cs

- s/logger/reporter/ in the description tooltip of Reporters
- Move CompositeReporter in ja.po
refs #78
---

Fix description tooltip of Reporters

---

README.md
README_ja.md

- Fix wording
- Add a general policy for accepting/rejecting new features.
The general policy is just my idea.
If necessary, I would like to discuss.
---

Mod README, add a general policy for accepting/rejecting new features.

---

Tests/Runtime/Agents/UGUIPlaybackAgentTest.cs

Infinite loops happen in tests using the Automated QA package when run on Linux player.
Ignore tests using AQA on Linux player.
---

Ignore tests using AQA when run on Linux player

---

README.md
README_ja.md
Runtime/Agents/OneTimeAgent.cs
Runtime/Attributes/InitializeOnLaunchAutopilotAttribute.cs
Runtime/Autopilot.cs
Runtime/ExitCode.cs
Runtime/Launcher.cs
Runtime/Loggers/ConsoleLoggerAsset.cs
Runtime/Loggers/FileLoggerAsset.cs
Tests/Runtime/Agents/OneTimeAgentTest.cs
Tests/Runtime/LauncherTest.cs
Tests/Runtime/Loggers/ConsoleLoggerAssetTest.cs
Tests/Runtime/Loggers/FileLoggerAssetTest.cs
Tests/Runtime/TestDoubles/SpyInitializeOnLaunchAutopilot.cs

- Add callback-order parameter into InitializeOnLaunchAutopilotAttribute
- Call initialize methods by ordered
- Using TypeCache when Unity 2021.3 or newer
- Logger's initialization is earliest
- Fix to remove unnecessary field reset
- Non-public field and property is not serialized in OneTimeAgent, ConsoleLogger, and FileLogger
- Fix to cancel launching autopilot when initialize failed
I hope to review && merge in this week.
---

Add callback-order parameter into InitializeOnLaunchAutopilotAttribute

---

Editor/Commandline.cs
Runtime/Launcher.cs
Runtime/Settings/AutopilotSettings.cs

Call override by commandline args method on launch player build from commandline.
I hope to your review && merge ASAP.
---

Fix override by commandline args not work on player build

---

Editor/Commandline.cs
Runtime/Autopilot.cs
Runtime/Launcher.cs
Runtime/Settings/AutopilotSettings.cs

- Fix to Not cancel TeardownLaunchAutopilotAsync method on terminates
- Fix using NUnit.Framework in runtime
- Fix log exit code to integer value
I hope to review && merge ASAP (Tuesday onwards).
---

Fix terminate process and player build failure

---

Editor/Localization/ja.po
Editor/UI/Settings/AutopilotSettingsEditor.cs
README.md
README_ja.md
Runtime/AgentDispatcher.cs
Runtime/Autopilot.cs
Runtime/Settings/AutopilotSettings.cs
Tests/Runtime/AgentDispatcherTest.cs
Tests/Runtime/Settings/AutopilotSettingsTest.cs

- ObserverAgent can set a single Agent.
- ObserverAgent is dispatched when loading any scene and disposes when unloading that scene.
- Multiple agents can be set in SceneCrossingAgents.
- SceneCrossingAgents will have the same lifespan as Autopilot (i.e., use `DontDestroyOnLoad`).
---

Add SceneCrossingAgents (ObserverAgent is obsolete)

---

Runtime/Agents/ErrorHandlerAgent.cs
Runtime/Agents/OneTimeAgent.cs
Runtime/Agents/TimeBombAgent.cs
Runtime/Agents/UGUIMonkeyAgent.cs

Not reset instance fields (not serialized) in ScriptableObjects when domain reloading is disabled.
Reset all instance fields (not serialized) in ScriptableObjects when even domain reloading is disabled.
---

Fix to reset instances when domain reloading is disabled

---

Editor/Commandline.cs
Editor/UI/Settings/AutopilotSettingsEditor.cs
README.md
README_ja.md
Runtime/Autopilot.cs
Runtime/Launcher.cs

The `AutopilotState` asset still contained information that the autopilot was running, so it had to be reset.
Condition: When a user stops Play Mode while the Autopilot is running.
Reset the `AutopilotState` when Play Mode is stopped while the Autopilot is running,
using `EditorApplication.playModeStateChanged` event.
This behavior was tested enable and disable domain reloading in Enter Play Mode Settings.
Minor fixes: Improved the exit process when launching from the commandline.
---

Teardown when Play Mode is stopped while the Autopilot running

---

Editor/UI/Settings/AutopilotSettingsEditor.cs
Runtime/Launcher.cs
Runtime/Settings/AutopilotSettings.cs
Runtime/Settings/AutopilotState.cs

Fix to not call `AssetDatabase.SaveAssetIfDirty()` in Unity 2020.2 or older.
This API is added in Unity 2020.3.
Not offer an alternative because this is an optional feature.
refs #110 #111 
---

Fix to support Unity 2020.2 or older

---

Editor/UI/Settings/AutopilotSettingsEditor.cs
Runtime/Launcher.cs
Runtime/Settings/AutopilotState.cs

Set a dirty flag when changing `AutopilotState`.
Ensuring state reflection when using MPPM packages.
This fix is being made because the correction in #110 is insufficient.
I hope to your review && merge in this week.
---

Set dirty flag when change AutopilotState

---

Runtime/Autopilot.cs
Runtime/Loggers/AbstractLoggerAsset.cs
Runtime/Loggers/CompositeLoggerAsset.cs
Runtime/Loggers/ConsoleLoggerAsset.cs
Runtime/Loggers/FileLoggerAsset.cs
Tests/Runtime/Loggers/CompositeLoggerAssetTest.cs
Tests/Runtime/Loggers/ConsoleLoggerAssetTest.cs
Tests/Runtime/Loggers/FileLoggerAssetTest.cs
Tests/Runtime/TestDoubles/SpyLoggerAsset.cs

FileLogger doesn't work when Autopilot is stopped and re-run.
- Remove IDisposable from AbstractLoggerAsset
- Fix to find logger instance when reset logger
I hope to your review && merge && release v1.8 in this week.
refs #100 
---

Fix FileLogger doesn't work when Autopilot is stopped and re-run

---

Runtime/Utilities/PathUtils.cs
Tests/Runtime/Settings/AutopilotSettingsTest.cs
Tests/Runtime/Utilities/PathUtilsTest.cs

- Fix `OutputRootPath` when `outputRootPath` is null and on player
- Add tests
Low
---

Fix outputRootPath when outputRootPath is null and on player

---

Tests/Runtime/Loggers/FileLoggerAssetTest.cs

Dispose `FileLogHandler` before reading the file in tests.
This fixed need for Unity 2020 or older
Low
---

Fix tests for Unity 2020 or older

---

Runtime/Autopilot.cs
Runtime/Launcher.cs
Runtime/Settings/AutopilotState.cs
Tests/Runtime/AutopilotTest.cs

Throw `NUnit.Framework.AssertionException` when Autopilot fails in Play Mode tests.
Not thrown an exception.
Output LogException in the console.
Because throwing an exception in an async method that had been `Forget`.
Throw exception in `LaunchAutopilotAsync` method.
I hope to your review && merge && release this week.
---

Fix behavior after Autopilot failure in Play Mode tests

---

Tests/Runtime/AutopilotTest.cs

Two tests fail because Autopilot is not launching.
Because AutopilotSettings instance is destroyed.
Use test-helper package v1.1 (or newer) and Unity 2023.1 (or newer).
test-helper v1.1 changes return type of `SceneManagerHelper.LoadSceneAsync()` to `AsyncOperation`.
Then, using UnityEngine.Awaitable.Awaiter in Unity 2023.1 or newer. It has a bug that destroys ScriptableObject after await twice.
This bug was reported.
Load scenes before creating ScriptableObject instances.
Before #137
---

Workaround Awaitable.Awaiter bug

---

README.md
README_ja.md
Runtime/AgentDispatcher.cs
Tests/Runtime/AgentDispatcherTest.cs

Agent is not destroyed if the following sequence:
1. Mapped scene is additive-loaded (not activated)
2. Other scenes are additive-loaded (not unload mapped-scene because they are not single-loaded)
3. Unload mapped scene
See test case DispatchByScene_SceneUnloadWithoutBecomingActive_DisposeAgent in Tests/Runtime/AgentDispatcherTest.cs
`AgentInspector` object moves to mapped scene.
- Upgrade tests required test-helper package version to v1.1.1
- Using unloadOthers option in CreateSceneAttribute
I hope to your review && merge && release it in around one week.
---

Fix to Agent is not destroyed

---

Runtime/Agents/AbstractAgent.cs
Runtime/Agents/DoNothingAgent.cs
Runtime/Agents/ErrorHandlerAgent.cs
Runtime/Agents/OneTimeAgent.cs
Runtime/Agents/ParallelCompositeAgent.cs
Runtime/Agents/RepeatAgent.cs
Runtime/Agents/SerialCompositeAgent.cs
Runtime/Agents/TerminateAgent.cs
Runtime/Agents/TimeBombAgent.cs
Runtime/Agents/UGUIEmergencyExitAgent.cs
Runtime/Agents/UGUIMonkeyAgent.cs
Runtime/Agents/UGUIPlaybackAgent.cs
Runtime/Autopilot.cs
Runtime/Launcher.cs
Tests/Runtime/Agents/DoNothingAgentTest.cs
Tests/Runtime/Agents/OneTimeAgentTest.cs
Tests/Runtime/Agents/ParallelCompositeAgentTest.cs
Tests/Runtime/Agents/RepeatAgentTest.cs
Tests/Runtime/Agents/SerialCompositeAgentTest.cs
Tests/Runtime/Agents/UGUIMonkeyAgentTest.cs
Tests/Runtime/Agents/UGUIPlaybackAgentTest.cs

- Rename CancellationToken parameter/variable name from token to cancellationToken
- Fix log message (not use 三点リーダー)
Very low
---

Rename CancellationToken parameter/variable name

---

Runtime/Autopilot.cs
Tests/Runtime/AutopilotTest.cs
Tests/Runtime/TestDoubles/SpyTerminatable.cs

Mod `Autopilot.TerminateAsync` return type from `UniTask` to `UniTaskVoid`.
And remove parameter `CancellationToken`.
Generally, use the `TerminateAsync` method with `Forget()`.
Also, this prevents accidents such as accidentally passing a `CancellationToken` and canceling the termination.
I changed the method signature because I couldn't attach `ObsoleteAttribute` to the arguments, but since it's an internal method, I don't think I need to mark it as a "breaking changes".
Very low
---

Mod TerminateAsync return type UniTaskVoid and remove parameter CancellationToken

---

README.md
README_ja.md

Fail two tests in ErrorHandlerAgentTest with com.unity.test-framework package v1.4.0 or older.
Upgrade required com.unity.test-framework package version to v1.4.1
> In async tests, any failing logs will now first be evaluated after the async method has completed. (DSTR-839)
see: https://docs.unity3d.com/Packages/com.unity.test-framework@1.4/changelog/CHANGELOG.html#141---2023-11-13
Very low
---

Upgrade tests required com.unity.test-framewor to v1.4.1

---

.octocov.yml
Makefile

- Fix commandline argument `--burst-disable-compilation` is to be passed with two dashes
- Fix lcov.info path
Very low
---

Fix coverage option run on command-line

---

.github/workflows/test.yml

Add run tests workflow for forked repo.
This workflow has only a manual trigger.
I tried putting the workflow only on a specific branch of a forked repo, but it didn't work.
I hope to merge ASAP.
I do not need release.
---

Add run tests workflow, only manual trigger

---

Tests/Runtime/TestComponents/OutGameTutorialButton.cs
Tests/Runtime/TestDoubles/SpyAgent.cs
Tests/Runtime/TestDoubles/SpyAliveCountAgent.cs
Tests/Runtime/TestDoubles/SpyButton.cs
Tests/Runtime/TestDoubles/StubThrowingErrorFromNotMainThreadOnClick.cs
Tests/Runtime/TestDoubles/StubThrowingErrorOnClick.cs

Due to a regression in Unity (not sure when this started), specifying "" for name no longer hides, so I changed it to "/".
Bug reported: IN-96428
see: https://docs.unity3d.com/ScriptReference/AddComponentMenu-ctor.html
Low
---

Fix to Hide from "Add Component" picker

---

Editor/Localization/ja.po
Editor/UI/Reporters/SlackReporterEditor.cs
README.md
README_ja.md
Runtime/Reporters/Slack/Response/SlackResponse.cs
Runtime/Reporters/Slack/SlackAPI.cs
Runtime/Reporters/Slack/SlackMessageSender.cs
Runtime/Reporters/SlackReporter.cs
Tests/Runtime/TestDoubles/SpySlackAPI.cs

Slack channels must be specified by channel ID.
This constraint was added in #135 
Slack channel can be specified channel name or ID.
Got the channel ID from the post API response, so I used this to post the screenshot.
Test results: https://github.com/nowsprinting/Anjin/actions/runs/13395260447
Low.
I want to release after merging this and existing PR.
---

Fix to Slack channel can be specified channel name
